package bfst17.Enums;

import bfst17.Enums.POIclasification;
import org.omg.CORBA.UNKNOWN;

import java.io.Serializable;


public enum PointsOfInterest implements Serializable {
    AMENITY_BAR(POIclasification.FOOD_AND_DRINKS),
    AMENITY_CAFE(POIclasification.FOOD_AND_DRINKS),
    AMENITY_ICE_CREAM(POIclasification.FOOD_AND_DRINKS),
    AMENITY_RESTAURANT(POIclasification.FOOD_AND_DRINKS),
    AMENITY_FOOD_COURT(POIclasification.FOOD_AND_DRINKS),
    AMENITY_FAST_FOOD(POIclasification.FOOD_AND_DRINKS),
    AMENITY_DRINKING_WATER(POIclasification.FOOD_AND_DRINKS),
    AMENITY_PUB(POIclasification.FOOD_AND_DRINKS),
    AMENITY_LIBRARY(POIclasification.ATTRACTION),
    AMENITY_CINEMA(POIclasification.ATTRACTION),
    AMENITY_THEATRE(POIclasification.ATTRACTION),
    TOURISM_MUSEUM(POIclasification.ATTRACTION),
    HISTORIC_MEMORIAL(POIclasification.ATTRACTION),
    HISTORIC_MONUMENT(POIclasification.ATTRACTION),
    MAN_MADE_OBELISK(POIclasification.ATTRACTION),
    TOURISM_ARTWORK(POIclasification.ATTRACTION),
    AMENITY_NIGHTCLUB(POIclasification.FOOD_AND_DRINKS),
    LEISURE_GOLF_COURSE(POIclasification.ATTRACTION),
    LEISURE_MINIATURE_GOLF(POIclasification.ATTRACTION),
    LEISURE_WATER_PARK(POIclasification.ATTRACTION),
    AMENITY_TOILETS(POIclasification.UTILITIES),
    AMENITY_BBQ(POIclasification.FOOD_AND_DRINKS),
    TOURISM_CAMP_SITE(POIclasification.ATTRACTION),
    TOURISM_INFORMATION(POIclasification.UTILITIES),
    TOURISM_HOSTEL(POIclasification.UTILITIES),
    TOURISM_HOTEL(POIclasification.UTILITIES),
    TOURISM_MOTEL(POIclasification.UTILITIES),
    AMENITY_ATM(POIclasification.UTILITIES),
    AMENITY_BANK(POIclasification.UTILITIES),
    AMENITY_DENTIST(POIclasification.HEALTH_CARE),
    AMENITY_DOCTORS(POIclasification.HEALTH_CARE),
    AMENITY_CLINIC(POIclasification.HEALTH_CARE),
    AMENITY_VETERINARY(POIclasification.HEALTH_CARE),
    AMENITY_HOSPITAL(POIclasification.HEALTH_CARE),
    AMENITY_PHARMACY(POIclasification.HEALTH_CARE),
    AMENITY_EMERGENCY_PHONE(POIclasification.EMERGENCY),
    AMENITY_FIRE_STATION(POIclasification.EMERGENCY),
    AMENITY_CAR_RENTAL(POIclasification.UTILITIES),
    AMENITY_PARKING(POIclasification.UTILITIES),
    AMENITY_FUEL(POIclasification.UTILITIES),
    AMENITY_CHARGING_STATION(POIclasification.UTILITIES),
    AMENITY_BUS_STATION(POIclasification.UTILITIES),
    RAILWAY_STATION(POIclasification.UTILITIES),
    NATURAL_VOLCANO(POIclasification.NATURE),
    NATURAL_CAVE_ENTRANCE(POIclasification.NATURE),
    NATURAL_SPRING(POIclasification.NATURE),
    AMENITY_POLICE(POIclasification.UTILITIES),
    AMENITY_EMBASSY(POIclasification.UTILITIES),
    SHOP_BAKERY(POIclasification.SHOPS),
    SHOP_GREENGROCER(POIclasification.SHOPS),
    SHOP_FARM(POIclasification.SHOPS),
    SHOP_SEAFOOD(POIclasification.SHOPS),
    SHOP_BUTCHER(POIclasification.SHOPS),
    SHOP_ALCOHOL(POIclasification.SHOPS),
    SHOP_WINE(POIclasification.SHOPS),
    SHOP_BEVERAGES(POIclasification.SHOPS),
    SHOP_ICE_CREAM(POIclasification.SHOPS),
    SHOP_CONVENIENCE(POIclasification.SHOPS),
    SHOP_SUPERMARKET(POIclasification.SHOPS),
    SHOP_DEPARTMENT_STORE(POIclasification.SHOPS),
    SHOP_BOOKS(POIclasification.SHOPS),
    SHOP_KIOSK(POIclasification.SHOPS),
    SHOP_CLOTHES(POIclasification.SHOPS),
    SHOP_FASHION(POIclasification.SHOPS),
    SHOP_LAUNDRY(POIclasification.SHOPS),
    SHOP_SHOES(POIclasification.SHOPS),
    SHOP_OPTICIAN(POIclasification.SHOPS),
    SHOP_JEWELRY(POIclasification.SHOPS),
    SHOP_PET(POIclasification.SHOPS),
    SHOP_TOYS(POIclasification.SHOPS),
    SHOP_ART(POIclasification.SHOPS),
    SHOP_PHOTO(POIclasification.SHOPS),
    SHOP_MUSICAL_INSTRUMENT(POIclasification.SHOPS),
    SHOP_FURNITURE(POIclasification.SHOPS),
    SHOP_ELECTRONICS(POIclasification.SHOPS),
    SHOP_HIFI(POIclasification.SHOPS),
    SHOP_MOBILE_PHONE(POIclasification.SHOPS),
    SHOP_DOITYOURSELF(POIclasification.SHOPS),
    SHOP_HARDWARE(POIclasification.SHOPS),
    SHOP_OUTDOOR(POIclasification.SHOPS),
    SHOP_SPORTS(POIclasification.SHOPS),
    SHOP_BICYCLE(POIclasification.SHOPS),
    SHOP_CAR(POIclasification.SHOPS),
    SHOP_CAR_REPAIR(POIclasification.SHOPS),
    AMENITY_CAR_WASH(POIclasification.UTILITIES),
    SHOP_CAR_PARTS(POIclasification.SHOPS),
    SHOP_TRAVEL_AGENCY(POIclasification.SHOPS),
    SHOP_TOBACCO(POIclasification.SHOPS),
    SHOP_CHEMIST(POIclasification.SHOPS),
    SHOP_HAIRDRESSER(POIclasification.SHOPS),
    SHOP_BEAUTY(POIclasification.SHOPS),
    SHOP_COSMETICS(POIclasification.SHOPS),
    SHOP_PERFUMERY(POIclasification.SHOPS),
    UNKNOWN(POIclasification.SHOPS);

    private final POIclasification classification;
    PointsOfInterest(POIclasification classification){
        this.classification = classification;
    }
    public POIclasification getClassification(){return classification;}
}
